// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSGLQgko_tRrLAtsFjHO2zglR6kmsiPVw',
    appId: '1:791080158746:web:e1fbd3be0f876e811cb3a3',
    messagingSenderId: '791080158746',
    projectId: 'iburossy-doctors-app',
    authDomain: 'iburossy-doctors-app.firebaseapp.com',
    storageBucket: 'iburossy-doctors-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCghiEDCXf3fgnRU4o437TfHgZJ3AyyZeI',
    appId: '1:791080158746:android:912502f2295fcf501cb3a3',
    messagingSenderId: '791080158746',
    projectId: 'iburossy-doctors-app',
    storageBucket: 'iburossy-doctors-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP5UpoT0v6vwXUEehEQRSIbnuhGepvH38',
    appId: '1:791080158746:ios:d1bc0e8c58f456f21cb3a3',
    messagingSenderId: '791080158746',
    projectId: 'iburossy-doctors-app',
    storageBucket: 'iburossy-doctors-app.firebasestorage.app',
    iosBundleId: 'com.example.samarv',
  );
}
